import { getCorsHeaders } from "../cors";
import type { Env } from "../types";

const DEFAULT_ACTION_BLOCKS_DB_ID = "67fdab55-eb09-4a59-a54d-0503ba4efeda";
const DEFAULT_TIMETABLE_DB_ID = "bb705b97-60e4-49bc-b7ce-45270649c15e";
const NOTION_VERSION = "2022-06-28";
type ActionStatus = "Scheduled" | "In progress" | "Done" | "Skipped";
export interface ActionBlockInput { notionPageId?: string; occurrenceId: string; scheduleId?: string; action: string; category: "Study" | "Training" | "Personal"; status: ActionStatus; scheduledStart?: string | null; scheduledEnd?: string | null; contextPageId?: string | null; plannedMinutes?: number | null; actualMinutes?: number | null; priority?: "Must" | "Should" | "Could" | null; source?: "Schedule" | "Manual" | "Study Engine"; notes?: string; }
export interface TimetableInput { target?:"timetable"; notionPageId?:string; occurrenceId:string; scheduleId:string; activity:string; category:"Class"|"Study"|"Training"|"Personal"; scheduledStart:string; scheduledEnd?:string|null; location?:string; notes?:string; }
interface NotionPage { id:string; last_edited_time?:string; properties:Record<string,any>; }
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...getCorsHeaders()}})}
function richText(value:string){return value?[{type:"text",text:{content:value.slice(0,1900)}}]:[]}
function text(prop:any){const values=prop?.title||prop?.rich_text||[];return values.map((v:any)=>v?.plain_text||v?.text?.content||"").join("")}
async function notionFetch(env:Env,path:string,init:RequestInit={}){const response=await fetch("https://api.notion.com/v1"+path,{...init,headers:{Authorization:`Bearer ${env.NOTION_TOKEN}`,"Notion-Version":NOTION_VERSION,"Content-Type":"application/json",...(init.headers||{})}});if(!response.ok)throw new Error(`Notion ${response.status}: ${(await response.text()).slice(0,500)}`);return response.json() as Promise<any>}
export function toNotionProperties(item:ActionBlockInput):Record<string,unknown>{const properties:Record<string,unknown>={Action:{title:richText(item.action)},Status:{status:{name:item.status}},Category:{select:{name:item.category}},Scheduled:item.scheduledStart?{date:{start:item.scheduledStart,end:item.scheduledEnd||null}}:{date:null},"Planned minutes":{number:item.plannedMinutes??null},"Actual minutes":{number:item.actualMinutes??null},Source:{select:{name:item.source||"Schedule"}},"Occurrence ID":{rich_text:richText(item.occurrenceId)},"Schedule ID":{rich_text:richText(item.scheduleId||"")},Notes:{rich_text:richText(item.notes||"")}};if(item.contextPageId!==undefined)properties.Context={relation:item.contextPageId?[{id:item.contextPageId}]:[]};if(item.priority)properties.Priority={select:{name:item.priority}};return properties}
export function fromNotionPage(page:NotionPage){const p=page.properties||{};return{notionPageId:page.id,occurrenceId:text(p["Occurrence ID"])||`notion:${page.id}`,scheduleId:text(p["Schedule ID"])||null,contextPageId:p.Context?.relation?.[0]?.id||null,action:text(p.Action),category:p.Category?.select?.name||"Personal",status:p.Status?.status?.name||"Scheduled",scheduledStart:p.Scheduled?.date?.start||null,scheduledEnd:p.Scheduled?.date?.end||null,plannedMinutes:p["Planned minutes"]?.number??null,actualMinutes:p["Actual minutes"]?.number??null,priority:p.Priority?.select?.name||null,source:p.Source?.select?.name||"Manual",notes:text(p.Notes),lastEdited:page.last_edited_time||null}}
export function toTimetableProperties(item:TimetableInput):Record<string,unknown>{return{Activity:{title:richText(item.activity)},Scheduled:{date:{start:item.scheduledStart,end:item.scheduledEnd||null}},Category:{select:{name:item.category}},Location:{rich_text:richText(item.location||"")},"Schedule ID":{rich_text:richText(item.scheduleId)},"Occurrence ID":{rich_text:richText(item.occurrenceId)},Notes:{rich_text:richText(item.notes||"")}}}
export function fromTimetablePage(page:NotionPage){const p=page.properties||{},occurrenceId=text(p["Occurrence ID"])||`notion:${page.id}`,scheduleId=text(p["Schedule ID"])||`notion:${page.id}`;return{notionPageId:page.id,occurrenceId,scheduleId,activity:text(p.Activity)||"Untitled event",category:p.Category?.select?.name||"Personal",scheduledStart:p.Scheduled?.date?.start||null,scheduledEnd:p.Scheduled?.date?.end||null,location:text(p.Location),notes:text(p.Notes),lastEdited:page.last_edited_time||null}}
async function findByOccurrence(env:Env,dbId:string,occurrenceId:string):Promise<NotionPage|null>{const data=await notionFetch(env,`/databases/${dbId}/query`,{method:"POST",body:JSON.stringify({filter:{property:"Occurrence ID",rich_text:{equals:occurrenceId}},page_size:1})});return data.results?.[0]||null}
async function upsert(env:Env,dbId:string,item:ActionBlockInput){const page:NotionPage|null=item.notionPageId?{id:item.notionPageId,properties:{}}:await findByOccurrence(env,dbId,item.occurrenceId);const properties=toNotionProperties(item);if(page)return notionFetch(env,`/pages/${page.id}`,{method:"PATCH",body:JSON.stringify({properties})});return notionFetch(env,"/pages",{method:"POST",body:JSON.stringify({parent:{database_id:dbId},properties})})}
async function queryRange(env:Env,dbId:string,from?:string|null,to?:string|null){const filters:any[]=[];if(from)filters.push({property:"Scheduled",date:{on_or_after:from}});if(to)filters.push({property:"Scheduled",date:{on_or_before:to}});const data=await notionFetch(env,`/databases/${dbId}/query`,{method:"POST",body:JSON.stringify({...(filters.length?{filter:filters.length===1?filters[0]:{and:filters}}:{}),sorts:[{property:"Scheduled",direction:"ascending"}],page_size:100})});return(data.results||[]).map(fromNotionPage)}
async function queryTimetableRange(env:Env,dbId:string,from?:string|null,to?:string|null){const filters:any[]=[];if(from)filters.push({property:"Scheduled",date:{on_or_after:from}});if(to)filters.push({property:"Scheduled",date:{on_or_before:to}});const data=await notionFetch(env,`/databases/${dbId}/query`,{method:"POST",body:JSON.stringify({...(filters.length?{filter:filters.length===1?filters[0]:{and:filters}}:{}),sorts:[{property:"Scheduled",direction:"ascending"}],page_size:100})});return(data.results||[]).map(fromTimetablePage)}
async function upsertTimetable(env:Env,dbId:string,item:TimetableInput){const page:NotionPage|null=item.notionPageId?{id:item.notionPageId,properties:{}}:await findByOccurrence(env,dbId,item.occurrenceId),properties=toTimetableProperties(item);if(page)return notionFetch(env,`/pages/${page.id}`,{method:"PATCH",body:JSON.stringify({properties})});return notionFetch(env,"/pages",{method:"POST",body:JSON.stringify({parent:{database_id:dbId},properties})})}
export async function handleActionBlocks(request:Request,env:Env):Promise<Response>{if(!env.NOTION_TOKEN)return json({configured:false,error:"Notion integration not configured"},501);const url=new URL(request.url),actionDb=env.ACTION_BLOCKS_DB_ID||DEFAULT_ACTION_BLOCKS_DB_ID,timetableDb=DEFAULT_TIMETABLE_DB_ID;try{if(url.searchParams.get("target")==="timetable"){if(request.method==="GET")return json({configured:true,timetableItems:await queryTimetableRange(env,timetableDb,url.searchParams.get("from"),url.searchParams.get("to"))});if(request.method!=="POST")return json({error:"Method not allowed"},405);const body=await request.json() as {items?:TimetableInput[]},incoming=Array.isArray(body.items)?body.items.slice(0,100):[],items=[];for(const item of incoming){if(!item?.occurrenceId||!item?.scheduleId||!item?.activity||!item?.scheduledStart)continue;items.push(fromTimetablePage(await upsertTimetable(env,timetableDb,item)))}return json({configured:true,timetableItems:items,count:items.length})}if(request.method==="GET"){const [items,timetableItems]=await Promise.all([queryRange(env,actionDb,url.searchParams.get("from"),url.searchParams.get("to")),queryTimetableRange(env,timetableDb,url.searchParams.get("from"),url.searchParams.get("to")).catch(()=>[])]);return json({configured:true,items,timetableItems})}if(request.method==="POST"){const body=await request.json() as {items?:Array<ActionBlockInput|TimetableInput>},incoming=Array.isArray(body.items)?body.items.slice(0,100):[],items=[],timetableItems=[];for(const raw of incoming){if((raw as TimetableInput)?.target==="timetable"||"activity" in raw){const item=raw as TimetableInput;if(!item?.occurrenceId||!item?.scheduleId||!item?.activity||!item?.scheduledStart)continue;timetableItems.push(fromTimetablePage(await upsertTimetable(env,timetableDb,item)));continue}const item=raw as ActionBlockInput;if(!item?.occurrenceId||!item?.action||(!item.scheduledStart&&!item.contextPageId))continue;items.push(fromNotionPage(await upsert(env,actionDb,item)))}return json({configured:true,items,timetableItems})}return json({error:"Method not allowed"},405)}catch(error){return json({configured:true,error:"Notion action sync failed",detail:(error as Error).message},502)}}
