/* Action Blocks v1
   Deterministic bridge for timetable, to-do, SyncEngine, and Notion.
   No AI scheduling: only explicitly tracked schedule blocks become actions. */
(function(root){
'use strict';
var CATEGORIES=['class','study','training','personal'];
var pendingEditor=null,normalizing=false,lastDay='',lastNotionPayload='',notionTimer=null,activePrompt=null;
function pad(n){return String(n).padStart(2,'0')}
function dateKey(d){d=d||new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function parseList(value){if(Array.isArray(value))return value;if(typeof value==='string')try{var p=JSON.parse(value);return Array.isArray(p)?p:[]}catch(e){}return[]}
function inferCategory(block){
 var text=((block&&block.name)||'')+' '+((block&&block.description)||'');
 if(/\b(LAW|POLS|ECON|HIST|PSYC|SOC|PHIL|MATH|BIOL|CHEM|PHYS)\s*[- ]?\d{2,4}[A-Z]?\b/i.test(text)||/^\s*\d{2,4}[A-Z]?\s*[:\-–|]/.test(text))return'class';
 if(/\b(gym|workout|strength|lift|lifting|run|running|ruck|rucking|cardio|zone\s*2|interval|sprint|soccer|mobility|recovery|swim|rowing|pilates)\b/i.test(text))return'training';
 if(/\b(study|reading|readings|review|recall|outline|brief|flashcard|practice exam|assignment|research|writing)\b/i.test(text))return'study';
 return'personal';
}
function normalizeBlock(block){block=Object.assign({},block||{});var explicit=CATEGORIES.indexOf(block.category)>=0;block.category=explicit?block.category:inferCategory(block);if(typeof block.trackCompletion!=='boolean')block.trackCompletion=block.category==='study'||block.category==='training';return block}
function localIso(key,time){var d=String(key).split('-').map(Number),t=String(time||'00:00').split(':').map(Number);return new Date(d[0],(d[1]||1)-1,d[2]||1,t[0]||0,t[1]||0,0,0).toISOString()}
function minutes(start,end){function m(v){var p=String(v||'0:00').split(':');return(+p[0]||0)*60+(+p[1]||0)}return Math.max(1,m(end)-m(start))}
function timeBand(v){return v<=20?'quick':v<=45?'m30':v<=90?'m60':'deep'}
function categoryLabel(v){return v?v.charAt(0).toUpperCase()+v.slice(1):'Personal'}
function materializeToday(schedule,tasks,now){
 now=now||new Date();schedule=parseList(schedule).map(normalizeBlock);tasks=parseList(tasks).slice();var key=dateKey(now),day=now.getDay(),changed=false;
 schedule.forEach(function(block){if(!block.trackCompletion||block.category==='class'||!Array.isArray(block.days))return;block.days.filter(function(x){return+x.day===day}).forEach(function(entry){
  var oid='tt:'+block.id+':'+key,found=tasks.find(function(t){return t&&t.occurrenceId===oid}),duration=minutes(entry.start,entry.end),start=localIso(key,entry.start),end=localIso(key,entry.end),location=entry.location||block.location||'',notes=[block.description,location].filter(Boolean).join(' · ');
  if(found){if(!found.rescheduled){var next={text:block.name||found.text,category:block.category,scheduledStart:start,scheduledEnd:end,time:timeBand(duration),notes:notes,scheduleId:block.id};Object.keys(next).forEach(function(k){if(found[k]!==next[k]){found[k]=next[k];found.updatedAt=Date.now();changed=true}})}return}
  tasks.unshift({id:oid,text:block.name||'Scheduled action',pri:'should',time:timeBand(duration),due:'today',dueKey:key,setKey:key,done:false,doneAt:null,created:new Date(start).getTime(),updatedAt:Date.now(),order:new Date(start).getTime(),notes:notes,category:block.category,source:'timetable',scheduleId:block.id,occurrenceId:oid,scheduledStart:start,scheduledEnd:end,outcome:null,startNudgedAt:null,missedAskedAt:null,rescheduled:false});changed=true;
 })});return{tasks:tasks,changed:changed}
}
function shiftIso(iso,days){var d=new Date(iso);d.setDate(d.getDate()+days);return d.toISOString()}
function scheduleChanged(a,b){function base(x){return JSON.stringify({name:x.name,description:x.description,location:x.location,color:x.color,days:x.days})}return!a||base(a)!==base(b)}
function installSetBridge(){
 if(!root.SyncEngine||root.SyncEngine.__actionBlocksSetBridge)return;var raw=root.SyncEngine.set;
 root.SyncEngine.set=function(ns,key,value){
  if(ns==='timetable'&&key==='courses'&&Array.isArray(value)&&!normalizing){var prev=parseList(root.SyncEngine.get(ns,key)),next=value.map(normalizeBlock);if(pendingEditor){next.forEach(function(block){var old=prev.find(function(x){return x&&x.id===block.id});if(scheduleChanged(old,block)){block.category=pendingEditor.category;block.trackCompletion=pendingEditor.trackCompletion}});pendingEditor=null}value=next}
  var result=raw.call(root.SyncEngine,ns,key,value);if((ns==='timetable'&&key==='courses')||(ns==='todo'&&key==='tasks'))setTimeout(run,0);return result;
 };
 root.SyncEngine.__actionBlocksSetBridge=true;
}
function injectStyles(){if(document.getElementById('action-block-styles'))return;var s=document.createElement('style');s.id='action-block-styles';s.textContent='.ab-track{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:38px}.ab-check{accent-color:#8b5cf6;width:16px;height:16px}.ab-toast{position:fixed;left:50%;bottom:16px;z-index:10020;transform:translateX(-50%);max-width:min(360px,calc(100vw - 24px));padding:10px 14px;border:1px solid rgba(139,92,246,.24);border-radius:12px;background:rgba(24,20,38,.96);color:#f4f0ff;font:500 12px/1.4 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 12px 36px rgba(0,0,0,.32);backdrop-filter:blur(18px)}.ab-modal{position:fixed;inset:0;z-index:10030;display:flex;align-items:center;justify-content:center;padding:16px;background:rgba(5,4,10,.38);backdrop-filter:blur(8px)}.ab-card{width:min(380px,100%);padding:18px;border:1px solid rgba(139,92,246,.22);border-radius:18px;background:rgba(22,18,35,.98);color:#f5f2ff;box-shadow:0 20px 60px rgba(0,0,0,.4);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.ab-card b{display:block;font-size:14px;margin-bottom:6px}.ab-card p{margin:0 0 14px;color:rgba(245,242,255,.66);font-size:12px;line-height:1.5}.ab-actions{display:flex;gap:7px}.ab-actions button{flex:1;border:1px solid rgba(139,92,246,.22);border-radius:10px;padding:8px 6px;background:rgba(139,92,246,.1);color:#ddd6fe;font:600 10px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;cursor:pointer}.ab-actions button:first-child{background:#7c3aed;color:white}.week-pill.action-done{opacity:.58}.week-pill.action-done:after{content:"✓";margin-left:4px;font-weight:700}';document.head.appendChild(s)}
function installTimetableEditor(){
 var loc=document.getElementById('fLoc'),save=document.getElementById('fSave');if(!loc||!save||document.getElementById('fCategory'))return;var host=loc.parentElement&&loc.parentElement.parentElement;if(!host)return;var row=document.createElement('div');row.className='f-row';row.innerHTML='<div><label class="f-label">Category</label><select class="f-input" id="fCategory"><option value="class">Class</option><option value="study">Study</option><option value="training">Training</option><option value="personal">Personal</option></select></div><div><label class="f-label">To-do</label><label class="ab-track"><span>Track completion</span><input class="ab-check" id="fTrack" type="checkbox"></label></div>';host.insertAdjacentElement('afterend',row);
 var cat=document.getElementById('fCategory'),track=document.getElementById('fTrack'),name=document.getElementById('fName'),touched=false,lastSig='';
 function defaults(value){cat.value=value;track.checked=value==='study'||value==='training'}
 function syncEditor(){var sig=String(save.textContent)+'|'+String(name&&name.value)+'|'+String(loc.value);if(sig===lastSig)return;lastSig=sig;touched=false;var list=parseList(root.SyncEngine&&root.SyncEngine.get('timetable','courses')),match=list.find(function(b){return b&&b.name===(name&&name.value)&&String(b.location||'')===String(loc.value||'')});if(match){match=normalizeBlock(match);cat.value=match.category;track.checked=match.trackCompletion}else defaults('class')}
 cat.addEventListener('change',function(){touched=true;track.checked=cat.value==='study'||cat.value==='training'});track.addEventListener('change',function(){touched=true});if(name)name.addEventListener('input',function(){if(!touched)defaults(inferCategory({name:name.value,description:(document.getElementById('fDesc')||{}).value||''}))});
 save.addEventListener('click',function(){pendingEditor={category:cat.value,trackCompletion:!!track.checked};if(track.checked&&'Notification'in root&&Notification.permission==='default')try{Notification.requestPermission()}catch(e){}},true);
 var clear=document.getElementById('fClear');if(clear)clear.addEventListener('click',function(){touched=false;lastSig='';defaults('class')});setInterval(syncEditor,350);syncEditor();
}
function normalizeSchedule(){if(!root.SyncEngine)return;var raw=parseList(root.SyncEngine.get('timetable','courses')),changed=raw.some(function(b){return CATEGORIES.indexOf(b&&b.category)<0||typeof b.trackCompletion!=='boolean'});if(changed){normalizing=true;root.SyncEngine.set('timetable','courses',raw.map(normalizeBlock));normalizing=false}}
function applyCompletionMarks(tasks){var key=dateKey(),day=(new Date()).getDay();document.querySelectorAll('.week-pill[data-id]').forEach(function(el){var oid='tt:'+el.getAttribute('data-id')+':'+key,t=tasks.find(function(x){return x&&x.occurrenceId===oid});el.classList.toggle('action-done',!!(t&&t.done&&+el.getAttribute('data-day')===day))})}
function materialize(){if(!root.SyncEngine)return;var schedule=root.SyncEngine.get('timetable','courses'),tasks=parseList(root.SyncEngine.get('todo','tasks')),result=materializeToday(schedule,tasks,new Date());if(result.changed)root.SyncEngine.set('todo','tasks',result.tasks);applyCompletionMarks(result.tasks);return result.tasks}
function showToast(message){var old=document.querySelector('.ab-toast');if(old)old.remove();var el=document.createElement('div');el.className='ab-toast';el.textContent=message;document.body.appendChild(el);setTimeout(function(){if(el.parentNode)el.remove()},5500)}
function writeTasks(tasks){root.SyncEngine.set('todo','tasks',tasks)}
function showMissed(task,tasks){if(activePrompt)return;activePrompt=task.id;task.missedAskedAt=Date.now();task.updatedAt=Date.now();writeTasks(tasks);var modal=document.createElement('div');modal.className='ab-modal';modal.innerHTML='<div class="ab-card" role="dialog" aria-modal="true"><b>'+escapeHtml(task.text||'Scheduled action')+'</b><p>This block is still open. Choose once, then the reminder will stay quiet.</p><div class="ab-actions"><button data-ab="tomorrow">Tomorrow</button><button data-ab="skip">Skip</button><button data-ab="keep">Keep open</button></div></div>';modal.addEventListener('click',function(e){var action=e.target&&e.target.getAttribute('data-ab');if(!action)return;var list=parseList(root.SyncEngine.get('todo','tasks')),current=list.find(function(x){return x&&x.id===task.id});if(current){if(action==='tomorrow'){current.scheduledStart=shiftIso(current.scheduledStart,1);current.scheduledEnd=shiftIso(current.scheduledEnd,1);current.due='tomorrow';current.dueKey=dateKey(new Date(current.scheduledStart));current.rescheduled=true;current.missedAskedAt=null}else if(action==='skip'){current.done=true;current.doneAt=Date.now();current.outcome='skipped'}current.updatedAt=Date.now();writeTasks(list)}activePrompt=null;modal.remove()});document.body.appendChild(modal)}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function checkPrompts(tasks){var now=Date.now();parseList(tasks).some(function(t){if(!t||t.done||!t.scheduledStart)return false;var start=Date.parse(t.scheduledStart),end=Date.parse(t.scheduledEnd||t.scheduledStart);if(!t.startNudgedAt&&now>=start&&now-start<=5*60*1000){t.startNudgedAt=now;t.updatedAt=now;writeTasks(tasks);showToast('Time to start: '+t.text);if('Notification'in root&&Notification.permission==='granted')try{new Notification('Time to start',{body:t.text,tag:t.occurrenceId||t.id})}catch(e){}return true}if(!t.missedAskedAt&&now>=end+30*60*1000&&dateKey(new Date(start))===dateKey(new Date())){showMissed(t,tasks);return true}return false})}
function cap(v){return v?String(v).charAt(0).toUpperCase()+String(v).slice(1):null}
function notionPayload(tasks){return parseList(tasks).filter(function(t){return t&&t.occurrenceId&&t.scheduledStart}).map(function(t){var duration=Math.max(1,Math.round((Date.parse(t.scheduledEnd||t.scheduledStart)-Date.parse(t.scheduledStart))/60000));return{notionPageId:t.notionPageId||undefined,occurrenceId:t.occurrenceId,scheduleId:t.scheduleId||undefined,action:t.text||'Scheduled action',category:cap(t.category)||'Personal',status:t.outcome==='skipped'?'Skipped':t.done?'Done':'Scheduled',scheduledStart:t.scheduledStart,scheduledEnd:t.scheduledEnd||null,plannedMinutes:duration,actualMinutes:t.actualMinutes||null,priority:cap(t.pri),source:t.source==='timetable'?'Schedule':'Manual',notes:t.notes||''}})}
function mergeNotion(remote){var tasks=parseList(root.SyncEngine.get('todo','tasks')),changed=false;parseList(remote).forEach(function(r){if(!r||!r.scheduledStart)return;var oid=r.occurrenceId||('notion:'+r.notionPageId),t=tasks.find(function(x){return x&&((x.occurrenceId&&x.occurrenceId===oid)||(x.notionPageId&&x.notionPageId===r.notionPageId))});if(!t){tasks.push({id:oid,text:r.action||'Notion action',pri:(r.priority||'').toLowerCase()||null,time:r.plannedMinutes<=20?'quick':r.plannedMinutes<=45?'m30':r.plannedMinutes<=90?'m60':'deep',dueKey:dateKey(new Date(r.scheduledStart)),setKey:dateKey(new Date(r.scheduledStart)),done:r.status==='Done'||r.status==='Skipped',doneAt:r.status==='Done'||r.status==='Skipped'?Date.now():null,created:Date.parse(r.scheduledStart),updatedAt:Date.now(),notes:r.notes||'',category:(r.category||'Personal').toLowerCase(),source:'notion',occurrenceId:oid,notionPageId:r.notionPageId,scheduledStart:r.scheduledStart,scheduledEnd:r.scheduledEnd,outcome:r.status==='Skipped'?'skipped':null});changed=true;return}if(r.notionPageId&&t.notionPageId!==r.notionPageId){t.notionPageId=r.notionPageId;changed=true}if((r.status==='Done'||r.status==='Skipped')&&!t.done){t.done=true;t.doneAt=Date.now();t.outcome=r.status==='Skipped'?'skipped':null;changed=true}});if(changed)writeTasks(tasks);return tasks}
function range(days){var d=new Date();d.setDate(d.getDate()+days);return dateKey(d)}
function syncNotion(tasks){if(!root.SyncEngine||typeof root.SyncEngine.fetchActionBlocks!=='function'||typeof root.SyncEngine.syncActionBlocks!=='function')return;clearTimeout(notionTimer);notionTimer=setTimeout(function(){root.SyncEngine.fetchActionBlocks(range(-1),range(2)).then(function(res){var merged=mergeNotion(res&&res.items);var payload=notionPayload(merged||tasks),token=JSON.stringify(payload);if(token===lastNotionPayload)return;lastNotionPayload=token;return root.SyncEngine.syncActionBlocks(payload)}).then(function(res){if(res&&res.items)mergeNotion(res.items)}).catch(function(){})},1600)}
function run(){if(!root.SyncEngine)return;normalizeSchedule();var tasks=materialize()||parseList(root.SyncEngine.get('todo','tasks'));checkPrompts(tasks);syncNotion(tasks);lastDay=dateKey()}
function boot(){installSetBridge();injectStyles();installTimetableEditor();if(root.SyncEngine&&root.SyncEngine.onReady)root.SyncEngine.onReady(function(){run();if(root.SyncEngine.subscribe){root.SyncEngine.subscribe('timetable','courses',run);root.SyncEngine.subscribe('todo','tasks',function(v){applyCompletionMarks(parseList(v));syncNotion(v)})}});setInterval(function(){if(lastDay!==dateKey())run();else{var tasks=parseList(root.SyncEngine&&root.SyncEngine.get('todo','tasks'));checkPrompts(tasks);applyCompletionMarks(tasks)}},30000)}
root.ActionBlocks={categories:CATEGORIES,dateKey:dateKey,parseList:parseList,inferCategory:inferCategory,normalizeBlock:normalizeBlock,materializeToday:materializeToday,shiftIso:shiftIso,categoryLabel:categoryLabel,run:run};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(typeof window!=='undefined'?window:globalThis);
