(function(){
  "use strict";
  var seenPast={},seenLive={};
  try{seenPast=JSON.parse(sessionStorage.getItem("timetable_polish_past")||"{}");seenLive=JSON.parse(sessionStorage.getItem("timetable_polish_live")||"{}")}catch(error){}
  function save(){try{sessionStorage.setItem("timetable_polish_past",JSON.stringify(seenPast));sessionStorage.setItem("timetable_polish_live",JSON.stringify(seenLive))}catch(error){}}
  function styles(){if(document.getElementById("timetablePolishStyles"))return;var style=document.createElement("style");style.id="timetablePolishStyles";style.textContent='.card{overflow:hidden}.card.past{opacity:.78!important;filter:saturate(.18) contrast(.96)!important;background:linear-gradient(150deg,color-mix(in srgb,var(--text-3) 8%,var(--surface)),var(--surface-2))!important;border-color:color-mix(in srgb,var(--text-3) 26%,var(--line))!important}.card.past:hover{opacity:.92!important}.card.past .bar{background:linear-gradient(180deg,color-mix(in srgb,var(--text-2) 55%,#fff),var(--text-3))!important}.card.past .name{color:var(--text-2)!important}.card.past .time,.card.past .meta{color:var(--text-3)!important}.card.past .chip{color:var(--text-2)!important;background:color-mix(in srgb,var(--text-3) 10%,transparent)!important;border-color:color-mix(in srgb,var(--text-3) 24%,transparent)!important}.completion-mark{position:absolute;z-index:3;top:10px;right:11px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;border:1px solid color-mix(in srgb,var(--text-3) 35%,var(--line));background:color-mix(in srgb,var(--surface) 88%,var(--text-3) 12%);color:var(--text-2);font:800 13px Inter,system-ui;box-shadow:inset 0 1px 0 var(--highlight)}.card.polish-finished::before{content:"";position:absolute;z-index:2;inset:-35% auto -35% -28%;width:22%;pointer-events:none;transform:skewX(-18deg);background:linear-gradient(90deg,transparent,rgba(255,255,255,.48),transparent);animation:finishSweep .82s var(--ease) both}.card.polish-finished .completion-mark{animation:finishMark .62s var(--spring) .18s both}.card.polish-live-start{animation:eventStart .78s var(--spring) both}.card.live .chip{animation:liveBreathe 1.8s ease-in-out infinite}@keyframes finishSweep{from{left:-28%;opacity:0}25%{opacity:1}to{left:118%;opacity:0}}@keyframes finishMark{from{opacity:0;transform:scale(.45) rotate(-18deg)}to{opacity:1;transform:none}}@keyframes eventStart{0%{transform:translateY(4px) scale(.985);box-shadow:0 0 0 0 color-mix(in srgb,var(--c) 0%,transparent)}55%{transform:translateY(-2px) scale(1.012);box-shadow:0 0 0 6px color-mix(in srgb,var(--c) 13%,transparent)}100%{transform:none}}@keyframes liveBreathe{50%{box-shadow:0 0 0 4px color-mix(in srgb,var(--c) 10%,transparent)}}@media(prefers-reduced-motion:reduce){.card.polish-finished::before,.card.polish-finished .completion-mark,.card.polish-live-start,.card.live .chip{animation:none!important}}';document.head.appendChild(style)}
  function key(card){return(card.dataset.id||"")+":"+(card.dataset.date||card.dataset.sourceDate||"")}
  function scan(){document.querySelectorAll(".card.past").forEach(function(card){var k=key(card);if(!card.querySelector(".completion-mark")){var mark=document.createElement("span");mark.className="completion-mark";mark.textContent="✓";mark.setAttribute("aria-label","Completed");card.appendChild(mark)}if(!seenPast[k]){card.classList.add("polish-finished");seenPast[k]=Date.now()}});document.querySelectorAll(".card.live").forEach(function(card){var k=key(card);if(!seenLive[k]){card.classList.add("polish-live-start");seenLive[k]=Date.now()}});save()}
  function boot(){styles();scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
