(function(root){
  "use strict";
  var stringifyRestore=null,previewTimer=null;
  var months={january:0,jan:0,february:1,feb:1,march:2,mar:2,april:3,apr:3,may:4,june:5,jun:5,july:6,jul:6,august:7,aug:7,september:8,sept:8,sep:8,october:9,oct:9,november:10,nov:10,december:11,dec:11};
  var weekdays={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6};
  function pad(value){return String(value).padStart(2,"0")}
  function dateKey(date){return date.getFullYear()+"-"+pad(date.getMonth()+1)+"-"+pad(date.getDate())}
  function localDate(key,time){var d=key.split("-").map(Number),t=time.split(":").map(Number);return new Date(d[0],d[1]-1,d[2],t[0],t[1]||0,0,0)}
  function clock(hour,minute,suffix){hour=Number(hour);minute=Number(minute||0);suffix=String(suffix||"").toLowerCase();if(suffix==="pm"&&hour<12)hour+=12;if(suffix==="am"&&hour===12)hour=0;return hour>23||minute>59?null:pad(hour)+":"+pad(minute)}
  function displayClock(value){var p=value.split(":").map(Number),h=p[0];return(h%12||12)+":"+pad(p[1])+" "+(h>=12?"PM":"AM")}
  function parseDate(text,now){var match,date=null;if((match=text.match(/\b(today|tonight|tomorrow)\b/i))){date=new Date(now);date.setHours(12,0,0,0);if(match[1].toLowerCase()==="tomorrow")date.setDate(date.getDate()+1)}else if((match=text.match(/\bin\s+(\d+)\s+(days?|weeks?)\b/i))){date=new Date(now);date.setHours(12,0,0,0);date.setDate(date.getDate()+Number(match[1])*(match[2].toLowerCase().startsWith("week")?7:1))}else if((match=text.match(/\b(20\d{2})-(\d{1,2})-(\d{1,2})\b/))){date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),12)}else if((match=text.match(/\b(january|jan|february|feb|march|mar|april|apr|may|june|jun|july|jul|august|aug|september|sept|sep|october|oct|november|nov|december|dec)\s+(\d{1,2})(?:st|nd|rd|th)?(?:,?\s+(\d{4}))?\b/i))){var year=Number(match[3])||now.getFullYear();date=new Date(year,months[match[1].toLowerCase()],Number(match[2]),12);if(!match[3]&&date<new Date(now.getFullYear(),now.getMonth(),now.getDate()))date.setFullYear(year+1)}else if((match=text.match(/\b(?:(next|this)\s+)?(sunday|monday|tuesday|wednesday|thursday|friday|saturday)\b/i))){date=new Date(now);date.setHours(12,0,0,0);var delta=(weekdays[match[2].toLowerCase()]-date.getDay()+7)%7;if(match[1]&&match[1].toLowerCase()==="next")delta+=7;else if(delta===0&&(!match[1]||match[1].toLowerCase()!=="this"))delta=7;date.setDate(date.getDate()+delta)}return date&&!Number.isNaN(date.getTime())?{key:dateKey(date),match:match,label:date.toLocaleDateString("en-CA",{weekday:"short",month:"short",day:"numeric"})}:null}
  function inferPair(match){var sh=Number(match[1]),sm=match[2],ss=match[3],eh=Number(match[4]),em=match[5],es=match[6];if(!ss&&es)ss=sh>eh?(es.toLowerCase()==="pm"?"am":"pm"):es;if(!es&&ss)es=ss;var start=clock(sh,sm,ss),end=clock(eh,em,es);return start&&end?{start:start,end:end}:null}
  function clean(text){return String(text||"").replace(/\s+/g," ").replace(/^(?:at|from|between|on|for)\s+/i,"").replace(/\s+(?:at|from|between|on|for)$/i,"").replace(/^[,;:\-–—]+|[,;:\-–—]+$/g,"").trim()}
  function parse(text,now){now=now instanceof Date?new Date(now):new Date();var original=String(text||"").trim(),range=original.match(/(?:\b(?:from|at|between)\s*)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(?:-|–|—|to|until|through|and)\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/i);if(!range)return null;var pair=inferPair(range);if(!pair)return null;var dateInfo=parseDate(original,now),key=dateInfo?dateInfo.key:dateKey(now),startDate=localDate(key,pair.start),endDate=localDate(key,pair.end);if(endDate<=startDate)endDate.setDate(endDate.getDate()+1);var minutes=Math.round((endDate-startDate)/60000);if(minutes<5||minutes>720)return null;var title=original.slice(0,range.index)+" "+original.slice(range.index+range[0].length);if(dateInfo&&dateInfo.match)title=title.replace(dateInfo.match[0]," ");title=clean(title)||"Scheduled task";return{text:title,dateKey:key,startTime:pair.start,endTime:pad(endDate.getHours())+":"+pad(endDate.getMinutes()),scheduledStart:startDate.toISOString(),scheduledEnd:endDate.toISOString(),duration:minutes,dateLabel:dateInfo?dateInfo.label:"Today",labels:[dateInfo?dateInfo.label:"Today",displayClock(pair.start)+" → "+displayClock(pair.end),minutes+" min","Timetable"]}}
  function parseList(value){if(Array.isArray(value))return value;try{var p=JSON.parse(value||"[]");return Array.isArray(p)?p:[]}catch(error){return[]}}
  function dueState(key){var today=new Date(),tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);return key===dateKey(today)?"today":key===dateKey(tomorrow)?"tomorrow":null}
  function timeBand(minutes){return minutes<=20?"quick":minutes<=45?"m30":minutes<=90?"m60":"deep"}
  function token(value){var hash=2166136261,text=String(value||"");for(var i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)}
  function apply(task,result){task.text=result.text;task.dueKey=result.dateKey;task.due=dueState(result.dateKey);task.setKey=dateKey(new Date());task.allDay=false;task.plannedMinutes=result.duration;task.time=timeBand(result.duration);task.scheduledStart=result.scheduledStart;task.scheduledEnd=result.scheduledEnd;task.reminderAt=result.scheduledStart;task.timeboxed=true;task.smartParsed=true;task.order=Date.parse(result.scheduledStart)||task.order;task.updatedAt=Date.now();return task}
  function syncTimetable(task){if(!root.SyncEngine)return;var start=new Date(task.scheduledStart),end=new Date(task.scheduledEnd),courses=parseList(root.SyncEngine.get("timetable","courses")),id="todo_action_"+token(task.occurrenceId||task.id),colours={must:"#be123c",should:"#c2410c",could:"#8b5cf6"};courses=courses.filter(function(block){return!block||(block.id!==id&&block.todoTaskId!==task.id)});courses.push({id:id,name:task.text,description:"Smart scheduled To-Do task",location:"",color:colours[task.pri]||"#8b5cf6",days:[{day:start.getDay(),start:pad(start.getHours())+":"+pad(start.getMinutes()),end:pad(end.getHours())+":"+pad(end.getMinutes()),location:""}],category:task.category||"study",trackCompletion:false,startDate:dateKey(start),endDate:dateKey(start),source:"todo-action-block",todoTaskId:task.id,occurrenceId:task.occurrenceId||task.id});root.SyncEngine.set("timetable","courses",courses)}
  function patch(result){if(stringifyRestore)stringifyRestore();var original=JSON.stringify,active=true;function restore(){if(!active)return;active=false;if(JSON.stringify===wrapped)JSON.stringify=original;stringifyRestore=null}function wrapped(value){if(active&&Array.isArray(value)){var task=null;value.forEach(function(item){if(item&&!item.done&&(!task||Number(item.created||0)>Number(task.created||0)))task=item});if(task){apply(task,result);var output=original.apply(JSON,arguments);restore();setTimeout(function(){syncTimetable(task)},0);return output}}return original.apply(JSON,arguments)}JSON.stringify=wrapped;stringifyRestore=restore;setTimeout(restore,1600)}
  function prepare(){var input=document.getElementById("inp");if(!input||!input.value.trim())return;var result=parse(input.value,new Date());if(!result)return;input.value=result.text;patch(result)}
  function preview(){clearTimeout(previewTimer);previewTimer=setTimeout(function(){var input=document.getElementById("inp"),row=document.getElementById("smartPreview");if(!input||!row)return;var result=parse(input.value,new Date());if(!result)return;row.innerHTML='<span class="smart-preview-label">Understood</span>'+result.labels.map(function(label){return'<span class="smart-preview-chip">'+label.replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})+'</span>'}).join('');row.hidden=false},120)}
  function bootRange(){var input=document.getElementById("inp");if(!input){setTimeout(bootRange,120);return}input.addEventListener("input",preview);preview()}
  root.TodoRangeSmart={parse:parse};document.addEventListener("keydown",function(event){if(event.key==="Enter"&&event.target&&event.target.id==="inp")prepare()},true);document.addEventListener("click",function(event){if(event.target.closest&&event.target.closest("#addbtn"))prepare()},true);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bootRange);else bootRange();
})(window);
(function(root){"use strict";function enableAutomatic(){var toggle=document.getElementById("smartAddToggle"),label=document.getElementById("smartAddLabel");if(toggle&&label&&String(label.textContent).trim().toLowerCase()==="off")toggle.click();if(toggle)toggle.remove();try{if(root.SyncEngine)root.SyncEngine.set("todo","smartAddSettings",JSON.stringify({enabled:true}))}catch(error){}}function boot(){enableAutomatic();new MutationObserver(enableAutomatic).observe(document.body,{childList:true,subtree:true})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot()})(window);
