import { readFile } from 'node:fs/promises';
import { dirname,join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const html=await readFile(join(root,'apps/athlete/athlete.html'),'utf8');
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
const shell=html.replace(/<script data-athlete-inline="[^"]+">[\s\S]*?<\/script>/g,'<script></script>').replace(/<style data-athlete-inline="[^"]+">[\s\S]*?<\/style>/g,'<style></style>');
assert(Buffer.byteLength(html)>120000,'Athlete output is unexpectedly small.');
assert(html.includes('single-file-v2.3'),'Athlete build marker is missing.');
assert(!/@import\b/i.test(html),'Athlete output contains a CSS @import.');
for(const id of ['app','profileView','trainView','progressView','ovrNum','bodyWrap','radar','attrList','logBtn','profileStartWorkout','startWorkoutBtn','recentWorkouts','progressExercise','progressChart','workoutSheet','workoutTitleInput','workoutExercises','addExerciseBtn','workoutFinishBtn','exercisePicker','exerciseSearch','setBw','setUnits','setRpeEnabled','ruckSettings','setExport','setImport','setReset','setSave'])assert(new RegExp(`id=["']${id}["']`).test(shell),`Missing #${id}.`);
const scripts=[...html.matchAll(/<script data-athlete-inline="([^"]+)">\n?([\s\S]*?)<\/script>/g)];
const expected=['core.js','athlete-body.js','athlete-data.js','athlete-training-data.js','athlete-render.js','athlete-flow.js','athlete-settings.js','athlete-training-ui.js','athlete-notion.js'];
assert(scripts.length===expected.length,`Expected ${expected.length} inline scripts.`);
for(let i=0;i<expected.length;i++){assert(scripts[i][1]===expected[i],`Script order mismatch at ${expected[i]}.`);new vm.Script(scripts[i][2],{filename:expected[i]});}
const readScript=name=>readFile(join(root,'apps/athlete/src/scripts',name),'utf8');
const [bodySource,dataSource,trainingSource]=await Promise.all(['athlete-body.js','athlete-data.js','athlete-training-data.js'].map(readScript));
const context={console,SyncEngine:{get:()=>null,set:()=>undefined}};context.window=context;vm.createContext(context);
vm.runInContext(bodySource,context);vm.runInContext(dataSource,context);vm.runInContext(trainingSource,context);
assert(vm.runInContext('TESTS.length',context)===12,'Expected 12 tests.');
assert(vm.runInContext('ATTRS.length',context)===8,'Expected eight attributes.');
assert(vm.runInContext("parsePace('12:30')",context)===750,'Pace parsing failed.');
assert(vm.runInContext("scoreOf(testById('run2400'),500,{v:500})",context)===70,'Scoring regression.');
console.log('Verified organized Athlete build, scripts, assessments and attributes.');
