import { readFile } from 'node:fs/promises';
import { dirname,join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const html=await readFile(join(root,'athlete.html'),'utf8');
function assert(condition,message){if(!condition)throw new Error(message);}
const shellOnly=html.replace(/<script data-athlete-inline="[^"]+">[\s\S]*?<\/script>/g,'<script></script>').replace(/<style data-athlete-inline="[^"]+">[\s\S]*?<\/style>/g,'<style></style>');
assert(Buffer.byteLength(html)>120000,'athlete.html is unexpectedly small.');
assert(html.includes('<meta name="athlete-build" content="single-file-v2.2">'),'The single-file build marker is missing.');
assert(!/@import\b/i.test(html),'The build contains a CSS @import.');
assert(!/(?:src|href)=["'](?:\.\/)?(?:core\.js|athlete(?:-body|-data|-training-data|-render|-flow|-settings|-training-ui)?\.js|athlete(?:-settings|-training)?\.css|theme-upgrade\.css)/i.test(shellOnly),'The build contains a local asset reference.');
for(const id of ['app','profileView','trainView','progressView','ovrNum','bodyWrap','radar','attrList','logBtn','profileStartWorkout','startWorkoutBtn','recentWorkouts','progressExercise','progressChart','workoutSheet','workoutTitleInput','workoutExercises','addExerciseBtn','workoutFinishBtn','exercisePicker','exerciseSearch','setBw','setUnits','setRpeEnabled','ruckSettings','setExport','setImport','setReset','setSave'])assert(new RegExp(`id=["']${id}["']`).test(shellOnly),`Required element #${id} is missing.`);
assert(shellOnly.includes('Training log')&&shellOnly.includes('Estimated 1RM over time'),'Training and progress views are missing.');
const scripts=[...html.matchAll(/<script data-athlete-inline="([^"]+)">\n?([\s\S]*?)<\/script>/g)];
const expected=['core.js','athlete-body.js','athlete-data.js','athlete-training-data.js','athlete-render.js','athlete-flow.js','athlete-settings.js','athlete-training-ui.js','athlete-notion.js'];
assert(scripts.length===expected.length,`Expected ${expected.length} inline scripts, found ${scripts.length}.`);
for(let i=0;i<expected.length;i++){assert(scripts[i][1]===expected[i],`Script order mismatch at ${expected[i]}.`);new vm.Script(scripts[i][2],{filename:`inline:${scripts[i][1]}`});}
const bodySource=await readFile(join(root,'athlete-body.js'),'utf8');
const dataSource=await readFile(join(root,'athlete-data.js'),'utf8');
const trainingSource=await readFile(join(root,'athlete-training-data.js'),'utf8');
const context={console,SyncEngine:{get:()=>null,set:()=>undefined}};context.window=context;vm.createContext(context);
vm.runInContext(bodySource,context,{filename:'athlete-body.js'});vm.runInContext(dataSource,context,{filename:'athlete-data.js'});vm.runInContext(trainingSource,context,{filename:'athlete-training-data.js'});
const invalidRegions=vm.runInContext(`Object.keys(BODY_DATA.regions).flatMap(function(code){return BODY_DATA.regions[code].filter(function(region){return !BODY_DATA.polys[region[0]]||!BODY_DATA.polys[region[0]][region[1]];}).map(function(region){return code+':'+region.join('/');});})`,context);
assert(invalidRegions.length===0,`Invalid body regions: ${invalidRegions.join(', ')}`);
assert(vm.runInContext('TESTS.length',context)===12,'The test catalogue should contain 12 tests.');assert(vm.runInContext('ATTRS.length',context)===8,'The athlete model should contain eight attributes.');assert(vm.runInContext("parsePace('12:30')",context)===750,'Pace parsing failed.');
assert(vm.runInContext("scoreOf(testById('run2400'),500,{v:500})",context)===70,'2400 m scoring regression.');
vm.runInContext(`ensureTrainingState();state.preferences.units='lb';var qaLoad=trainingLoadToKg(135);var qaSets=[0,1,2,3].map(function(i){return{id:'s'+i,loadKg:qaLoad,reps:8,rpe:8,type:'work',done:true};});var qaWorkout={id:'wqa',d:'2026-09-02',title:'QA',completedAt:1,exercises:[{id:'x',exerciseId:'bench',sets:qaSets}]};`,context);
assert(vm.runInContext('trainingRound(trainingKgToDisplay(qaLoad),1)',context)===135,'lb/kg conversion failed.');
assert(vm.runInContext('trainingRound(trainingKgToDisplay(trainingEstimate1RMKg(qaSets[0])),0)',context)===171,'Estimated 1RM regression.');
assert(vm.runInContext('trainingRound(trainingKgToDisplay(trainingWorkoutMetrics(qaWorkout).volumeKg),0)',context)===4320,'Workout volume regression.');
assert(vm.runInContext("trainingAssessmentCandidate({exerciseId:'bench',sets:[{loadKg:65,reps:8,type:'work',done:true}]}).testId",context)==='bench','Assessment promotion regression.');
console.log(`Verified athlete.html: ${scripts.length} scripts, workout logging, 1RM, volume, promotion, 12 assessments and 8 attributes valid.`);
